# Site settings
title: Enscience
email: ashwin@outplayedapps.com
description: > # this means to ignore newlines until "baseurl:"
  An online science encyclopedia that includes notes on various topics in math and science. Still a work in progress.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "enscience.me" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  epicfaace

# Build settings
markdown: kramdown

safe: false
redirects: yes

pgCategories:
- 'Biology'
- 'Chemistry'
- 'Physics'
- 'Mathematics'
- 'Geology'
- 'Astronomy'
- 'Computer Science'
- 'Other'

gems:
  - jekyll-redirect-from