# Site settings
title: Enscience
email: aramaswamis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An online science encyclopedia that includes notes on various topics in math and science. It is useful for quizbowl, or even just for those interested in learning new things in a new way.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "enscience.me" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

safe: false
redirects: yes

pgCategories:
- 'Chemistry'
- 'Geology'

gems:
  - jekyll-redirect-from